name = "website-harbor-heat-15-preview"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat", "nodejs_als"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "website-harbor-heat-15-preview-inventory"
database_id = "4ac51d4b-2d9e-4f6c-96d0-59ed4f74238e"

[[r2_buckets]]
binding = "PRODUCT_IMAGES"
bucket_name = "website-harbor-heat-15-images"

[[kv_namespaces]]
binding = "SESSION"
id = "2fb321aeb0ac47d9b9279be9c6559f36"
