name = "website-harbor-heat-15"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat", "nodejs_als"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "website-harbor-heat-15-inventory"
database_id = "6dcc9bf0-d206-4f03-916e-bc3e659a68d2"

[[r2_buckets]]
binding = "PRODUCT_IMAGES"
bucket_name = "website-harbor-heat-15-images"

[[kv_namespaces]]
binding = "SESSION"
id = "9a73f3c56d9d42b7b05c10a530264882"
