// Generated by Site Launchpad. Edit in the dashboard and export again.
import type { ClientConfigInput } from "./schema";

export const rawClientConfig: ClientConfigInput = {
  "deployMode": "client",
  "identity": {
    "name": "Harbor & Heat Spas",
    "shortName": "Harbor Heat",
    "foundedYear": 2011,
    "tagline": "Pacific Northwest hot tubs, swim spas, and recovery — try them on the lake.",
    "siteUrl": "https://www.harborandheatspas.com",
    "schemaType": "Store"
  },
  "contact": {
    "phone": "+15035550190",
    "phoneDisplayOverride": "(503) 555-0190",
    "smsPhone": "+15035550190",
    "email": "hello@harborandheatspas.com"
  },
  "address": {
    "street": "333 S State St",
    "street2": "Suite 200",
    "city": "Lake Oswego",
    "region": "OR",
    "postalCode": "97034",
    "country": "US",
    "latitude": 45.4178,
    "longitude": -122.6687,
    "googlePlaceId": "ChIJDemoHarborHeatLakeOswegoOR2011"
  },
  "hours": [
    {
      "days": [
        "Monday"
      ],
      "opens": "10:00",
      "closes": "18:00"
    },
    {
      "days": [
        "Tuesday"
      ],
      "opens": "10:00",
      "closes": "18:00"
    },
    {
      "days": [
        "Wednesday"
      ],
      "opens": "10:00",
      "closes": "18:00"
    },
    {
      "days": [
        "Thursday"
      ],
      "opens": "10:00",
      "closes": "18:00"
    },
    {
      "days": [
        "Friday"
      ],
      "opens": "10:00",
      "closes": "18:00"
    },
    {
      "days": [
        "Saturday"
      ],
      "opens": "09:00",
      "closes": "17:00"
    },
    {
      "days": [
        "Sunday"
      ],
      "opens": "11:00",
      "closes": "16:00"
    }
  ],
  "social": {
    "facebook": "https://www.facebook.com/harborandheatspas",
    "instagram": "https://www.instagram.com/harborandheatspas",
    "youtube": "https://www.youtube.com/@harborandheatspas",
    "tiktok": "https://www.tiktok.com/@harborandheatspas",
    "x": "https://x.com/harborandheat",
    "linkedin": "https://www.linkedin.com/company/harbor-and-heat-spas",
    "googleBusiness": "https://maps.google.com/?cid=harborandheatlakeoswego"
  },
  "brand": {
    "colors": {
      "primary": "#476A4E",
      "primaryMid": "#38583F",
      "deep": "#29442F",
      "night": "#1C3021",
      "abyss": "#101D14",
      "accent": "#C88952",
      "accentSoft": "#E0AE81",
      "accentDeep": "#A96938",
      "accentDark": "#76451F",
      "accentLift": "#EDC49E",
      "accentPress": "#A96332",
      "accentGlow": "#F6DDC4",
      "urgent": "#D7261E",
      "urgentLight": "#E8382F",
      "urgentDark": "#B71E17",
      "surface": "#FFFFFF",
      "surfaceAlt": "#F4F2E8",
      "ink": "#141927",
      "inkMuted": "#4A5268",
      "onDark": "#DCE9DE",
      "onDarkMuted": "#A9BEAC"
    },
    "fonts": {
      "display": "Fraunces",
      "body": "Source Sans 3",
      "mono": "IBM Plex Mono",
      "googleFontsHref": "https://fonts.googleapis.com/css2?family=Fraunces:wght@500;600;700&family=Source+Sans+3:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;700&display=swap"
    },
    "logos": {
      "nav": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/astro/navLogo-cf4af09d1456ba7169a50d42df92d94093045a263e04bd79898d7ceb346e4e50-5834700fab0c4254ab6340ce57113dd6.webp",
      "footer": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/astro/footerLogo-cf4af09d1456ba7169a50d42df92d94093045a263e04bd79898d7ceb346e4e50-cb75bd8d16584d488375c845aaa92140.webp",
      "inventory": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/astro/inventoryLogo-cf4af09d1456ba7169a50d42df92d94093045a263e04bd79898d7ceb346e4e50-bf2752b6727f4c2bb76c6a8c9bbaf9ad.webp",
      "favicon": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/astro/favicon-ffae7c3cd7ce47fd4512ea55f4ee67f8b623a5b092c90351176f9bb84a33a958-7bb48a4f38c546e6a73100f70ade8b28.webp",
      "ogImage": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/astro/ogImage-212a927d4f9b37b2d19cd27a459e9592a97e630f549ed06e8ce64e3bfac0f1d1-cb4c4d6527ba43e7937a8470bb9a76d9.webp"
    },
    "radius": {
      "card": 24,
      "button": 12,
      "pill": 999
    }
  },
  "nav": {
    "items": [
      {
        "type": "categories"
      },
      {
        "type": "link",
        "label": "Find Your Match",
        "href": "/find-your-match",
        "inHeader": true,
        "inFooter": true
      },
      {
        "type": "link",
        "label": "Inventory",
        "href": "/inventory",
        "inHeader": true,
        "inFooter": true
      },
      {
        "type": "link",
        "label": "Financing",
        "href": "/financing",
        "inHeader": true,
        "inFooter": true
      },
      {
        "type": "link",
        "label": "Visit Us",
        "href": "/visit-us",
        "inHeader": true,
        "inFooter": true
      }
    ],
    "primaryCta": {
      "label": "Shop Inventory",
      "href": "/inventory"
    },
    "legalItems": [
      {
        "label": "Privacy Policy",
        "href": "/privacy-policy"
      }
    ]
  },
  "categories": {
    "hot-tub": {
      "enabled": true,
      "label": "Hot Tubs",
      "blurb": "Deep-seat cedar-side spas for rainy Portland evenings — strong jets, tight covers, and models you can sit in today.",
      "heroImage": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/astro/categoryHotTubs-06fe445957f1cc0569e75bde772724e29e8e8263984b857d305e1e7a60b932b9-0795b50e7d094ff6bf252717b879b04b.webp",
      "sortOrder": 0
    },
    "swim-spa": {
      "enabled": true,
      "label": "Swim Spas",
      "blurb": "Year-round current training without a pool permit. Swim, recover, and soak in one backyard unit.",
      "heroImage": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/astro/categorySwimSpas-23d595d681228b5edce4a40b0fe71dd336e0ab4f2cef6675600ec3b2f04b1618-19786f98bcb7416f87cc6b761d2a9768.webp",
      "sortOrder": 1
    },
    "sauna": {
      "enabled": true,
      "label": "Saunas",
      "blurb": "Cedar infrared and traditional rooms sized for a garage, ADU, or covered patio.",
      "heroImage": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/astro/categorySaunas-85996537263a52097e0a4a432a7448513180f74b6bce8c18e99fd2a650bae54e-e108a8fa33534ba2ba7b5d682c3a163c.webp",
      "sortOrder": 2
    },
    "cold-plunge": {
      "enabled": true,
      "label": "Cold Plunge",
      "blurb": "Chilled plunge tubs for contrast after a soak, a run on the Springwater, or a long desk day.",
      "heroImage": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/astro/categoryColdPlunge-2b090227c15be9f7d365397057a7353ede5ea89f77c07dde2d3ee20a045ea7e0-038a26a364044b5b93ea75c5780b3d0c.webp",
      "sortOrder": 3
    },
    "massage-chair": {
      "enabled": true,
      "label": "Massage Chairs",
      "blurb": "Quiet zero-gravity chairs with heat and stretch programs for the den — not a gym lobby.",
      "heroImage": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/astro/categoryMassageChairs-eaa2da67e6834ea4f1e2be6d837bdeeb813ef08849302feca1b2350cf246494b-de4e3689422a4a2aae8d23a94744092b.webp",
      "sortOrder": 4
    }
  },
  "serviceAreas": [
    "Lake Oswego",
    "Portland",
    "West Linn",
    "Oregon City",
    "Tigard",
    "Tualatin",
    "Sherwood",
    "Lake Grove",
    "Dunthorpe",
    "Clackamas"
  ],
  "financing": {
    "headline": "Check my options",
    "blurb": "From about $139/month on a mid-size spa after delivery and setup.",
    "bullets": [
      "Promotional financing available on qualifying purchases of $2,500 or more. Terms from 24 to 60 months. Ask the Lake Oswego team for today's rates."
    ],
    "lenderName": "Wells Fargo Home Projects",
    "applyUrl": "https://retailservices.wellsfargo.com/",
    "disclaimer": "Subject to credit approval. Equal Housing Lender. Example payment is an estimate only and is not an offer of credit."
  },
  "display": {
    "showPrice": true,
    "showMonthly": true
  },
  "homepage": {
    "title": null,
    "description": null,
    "sections": [
      {
        "type": "announcement",
        "badge": "Harvest Soak Event",
        "text": "In-stock spas include Metro Portland delivery through November 30",
        "href": "/inventory"
      },
      {
        "type": "hero",
        "eyebrow": "Lake Oswego showroom",
        "headline": "The soak you can try before the rain sets in",
        "highlight": [
          "try before"
        ],
        "subhead": "Walk a floor of filled hot tubs, swim spas, saunas, and plunges. Leave with one written number — unit, delivery, and setup.",
        "bullets": [
          {
            "text": "Working models on the floor — sit in them before you buy",
            "superlative": false,
            "footnote": null
          },
          {
            "text": "Out-the-door pricing that includes delivery and professional setup",
            "superlative": false,
            "footnote": null
          },
          {
            "text": "Financing from about $139/month on qualifying spas",
            "superlative": false,
            "footnote": null
          }
        ],
        "backgroundImage": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/assets/hero-06fe445957f1cc0569e75bde772724e29e8e8263984b857d305e1e7a60b932b9-880988564474415bb6b87f732e54fccf.webp",
        "image": null,
        "promo": "Harvest event: complimentary Metro Portland delivery on in-stock spas through November 30.",
        "actions": [
          {
            "label": "Shop inventory",
            "href": "/inventory",
            "style": "primary"
          },
          {
            "label": "Request pricing",
            "href": "/find-your-match",
            "style": "secondary"
          }
        ],
        "leadCard": {
          "heading": "Get today's local price",
          "subtext": "Tell us seats, budget, and backyard access. We'll text current inventory and a written total.",
          "footnote": "What happens next: a specialist texts availability within one business hour. No spam, no hard sell."
        }
      },
      {
        "type": "stats",
        "items": [
          {
            "value": "15+",
            "label": "Years on the Willamette",
            "claim": null
          },
          {
            "value": "4.8★",
            "label": "Google rating",
            "claim": null
          },
          {
            "value": "72hr",
            "label": "Typical in-stock delivery",
            "claim": null
          },
          {
            "value": "100%",
            "label": "Written out-the-door price",
            "claim": null
          }
        ]
      },
      {
        "type": "offercard",
        "eyebrow": "Open 7 days in Lake Oswego",
        "heading": "There has never been a better week to sit in one",
        "body": "Every spa on the floor is filled and running. Compare jets, seating, and insulation with someone who delivers these in the rain.",
        "bullets": [
          {
            "text": "Sit in working models before you spend a dollar",
            "superlative": false,
            "footnote": null
          },
          {
            "text": "One written price: spa, delivery, crane if needed, and startup",
            "superlative": false,
            "footnote": null
          },
          {
            "text": "Flexible financing for most credit profiles",
            "superlative": false,
            "footnote": null
          },
          {
            "text": "Local water-care and service after the sale",
            "superlative": false,
            "footnote": null
          }
        ],
        "actions": [
          {
            "label": "See what's in stock",
            "href": "/inventory",
            "style": "primary"
          },
          {
            "label": "Plan a showroom visit",
            "href": "/visit-us",
            "style": "secondary"
          }
        ]
      },
      {
        "type": "products",
        "eyebrow": "In stock · no factory wait",
        "heading": "Showroom selection",
        "body": "These are units you can sit in today. Ask about current availability, covers, and steps.",
        "limit": 6,
        "category": null,
        "moreLink": {
          "label": "See the full floor",
          "href": "/inventory",
          "style": "primary"
        },
        "disclaimer": "Photos are representative. Serial numbers, options, and pricing are confirmed in the showroom."
      },
      {
        "type": "categories",
        "eyebrow": "Shop by ritual",
        "heading": "What are you adding to the backyard?",
        "body": "Hot tubs for wet-night soaks, swim spas for training, saunas and plunges for recovery, chairs for the den.",
        "showImages": true
      },
      {
        "type": "imagecards",
        "eyebrow": "Every line we sell is on the floor in Lake Oswego. Pick a path or walk them all.",
        "heading": "Start with the right category",
        "items": [
          {
            "title": "Hot Tubs",
            "body": "Deep seats, tight covers, and shells that stay warm in January.",
            "image": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/assets/hotTubs-90afe2daab67d1415fa369189bf803c1c2b1ff0f89965a9442d521946e03c8a1-6329c89000a044acb3a5248b65f6c4e1.webp",
            "href": "/hot-tubs"
          },
          {
            "title": "Swim Spas",
            "body": "Swim current plus a therapy seat — no pool required.",
            "image": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/assets/swimSpas-6dff4cfaf8629d52c258520d44523ac7731530383578531d977736074e5ea5f9-f69bb7a763164ab5addc9c30f3d877cd.webp",
            "href": "/swim-spas"
          },
          {
            "title": "Saunas",
            "body": "Cedar infrared and traditional rooms that fit a garage or patio.",
            "image": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/astro/categorySaunas-85996537263a52097e0a4a432a7448513180f74b6bce8c18e99fd2a650bae54e-e108a8fa33534ba2ba7b5d682c3a163c.webp",
            "href": "/saunas"
          },
          {
            "title": "Cold Plunge",
            "body": "Contrast therapy next to the spa, ready for backyard power.",
            "image": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/astro/categoryColdPlunge-2b090227c15be9f7d365397057a7353ede5ea89f77c07dde2d3ee20a045ea7e0-038a26a364044b5b93ea75c5780b3d0c.webp",
            "href": "/cold-plunges"
          },
          {
            "title": "Massage Chairs",
            "body": "Zero-gravity chairs with heat, stretch, and quiet motors.",
            "image": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/astro/categoryMassageChairs-eaa2da67e6834ea4f1e2be6d837bdeeb813ef08849302feca1b2350cf246494b-de4e3689422a4a2aae8d23a94744092b.webp",
            "href": "/massage-chairs"
          }
        ]
      },
      {
        "type": "imagecards",
        "eyebrow": "Find your fit",
        "heading": "Three ways to start",
        "items": [
          {
            "title": "Hot Tubs",
            "body": "Premium seating and hydrotherapy for 4–8 people.",
            "image": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/assets/hotTubs-90afe2daab67d1415fa369189bf803c1c2b1ff0f89965a9442d521946e03c8a1-6329c89000a044acb3a5248b65f6c4e1.webp",
            "href": "/hot-tubs"
          },
          {
            "title": "Swim Spas",
            "body": "Train, recover, and soak without a pool permit.",
            "image": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/assets/swimSpas-6dff4cfaf8629d52c258520d44523ac7731530383578531d977736074e5ea5f9-f69bb7a763164ab5addc9c30f3d877cd.webp",
            "href": "/swim-spas"
          },
          {
            "title": "Find Your Match",
            "body": "60-second quiz for seats, budget, and backyard access.",
            "image": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/assets/hero-06fe445957f1cc0569e75bde772724e29e8e8263984b857d305e1e7a60b932b9-880988564474415bb6b87f732e54fccf.webp",
            "href": "/find-your-match"
          }
        ]
      },
      {
        "type": "benefits",
        "heading": "Why neighbors drive to Lake Oswego",
        "items": [
          {
            "title": "Try before you buy",
            "body": "Sit in filled spas and feel the jet layout, not a brochure.",
            "icon": null
          },
          {
            "title": "One written total",
            "body": "Delivery, placement, and startup are in the quote.",
            "icon": null
          },
          {
            "title": "Rain-ready setup",
            "body": "We plan pads, covers, and electrical before the truck rolls.",
            "icon": null
          },
          {
            "title": "Local aftercare",
            "body": "Water-care visits and parts from the same team.",
            "icon": null
          }
        ]
      },
      {
        "type": "gallery",
        "heading": "From the showroom and recent installs",
        "images": [
          {
            "src": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/library/library-ae0cb8f27da8ea99f286b465f38114d85f748b5d135b04cd8e655eb8efc5ac87-184f5f6c481c4706ac283404ad3461d8.webp",
            "alt": "Showroom floor with filled spas"
          },
          {
            "src": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/library/library-18e493c00967b8d682494a5d4e75eff3424f374bf33482ad0557b19b71b3d024-77018a0224274e75b907657f93c88d73.webp",
            "alt": "Cedar sauna benches and heater"
          },
          {
            "src": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/library/library-637f0ebffc2e04ce8d2845e95f41bfe7f1da2899f6f7cd14a9053bb790e92378-fb8bd6373ffd40e89c54a4d32a1b4c7f.webp",
            "alt": "Outdoor cold plunge among evergreens"
          },
          {
            "src": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/library/library-9516f709fa509e44839b2632454f22fc348cd20860837e1269709c269381f649-2b9f2211763b4993a6e44a262361e71c.webp",
            "alt": "Leather massage chair"
          },
          {
            "src": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/library/library-d83bf997dd3581f6ab38528fdea3a275d3fd91f72fb33b4e1511ad2d0d69e2b3-da0ac2e4ab4b4fb9b83ef1e2fd742efa.webp",
            "alt": "Backyard swim spa"
          },
          {
            "src": "https://pub-8ee3a2ad3f984055a5a511f248031818.r2.dev/clients/15-harbor-heat-spas/library/library-3167c2d23a788d445501704b35814c5ffdb7ab65a4b471907095a53306b07dbe-a0f4f1c243da43e183439f815997c0d9.webp",
            "alt": "Underwater jet close-up"
          }
        ]
      },
      {
        "type": "reviews",
        "eyebrow": "Reviews",
        "heading": "What Portland families say",
        "items": [
          {
            "name": "Priya M.",
            "quote": "5",
            "rating": 5,
            "source": "Google Review",
            "date": "August 2026",
            "location": null,
            "detail": null
          },
          {
            "name": "Jonah K.",
            "quote": "5",
            "rating": 5,
            "source": "Google Review",
            "date": "July 2026",
            "location": null,
            "detail": null
          },
          {
            "name": "Elena S.",
            "quote": "5",
            "rating": 5,
            "source": "Google Review",
            "date": "June 2026",
            "location": null,
            "detail": null
          }
        ],
        "aggregate": {
          "rating": 4.8,
          "count": 142,
          "source": "Google"
        }
      },
      {
        "type": "comparison",
        "eyebrow": "Why buy local",
        "heading": "Harbor & Heat vs. a crate on a driveway",
        "body": "A spa is a 20-year backyard fixture. The difference is who shows up when the cover needs a clip or the water turns cloudy.",
        "usLabel": null,
        "themLabel": "Online marketplace",
        "rows": [
          {
            "label": "Try before you buy",
            "us": "Filled units on the floor",
            "them": "Photos and a spec sheet"
          },
          {
            "label": "Pricing",
            "us": "One written out-the-door number",
            "them": "Freight, crane, and startup later"
          },
          {
            "label": "Delivery",
            "us": "Local crew that knows Lake Oswego access",
            "them": "Curbside drop"
          },
          {
            "label": "After the sale",
            "us": "A cell phone that a tech answers",
            "them": "A ticket queue"
          }
        ]
      },
      {
        "type": "promise",
        "badgeValue": "100%",
        "badgeLabel": "Written price",
        "heading": "Straight numbers, no weekend close",
        "body": "We would rather send you home to think than push a same-day signature. Come with measurements and leave with a quote you can compare.",
        "bullets": [
          {
            "text": "Out-the-door pricing in writing",
            "superlative": false,
            "footnote": null
          },
          {
            "text": "No pressure, no hidden freight",
            "superlative": false,
            "footnote": null
          },
          {
            "text": "Local delivery and placement plan",
            "superlative": false,
            "footnote": null
          },
          {
            "text": "Water-care walkthrough on day one",
            "superlative": false,
            "footnote": null
          }
        ]
      },
      {
        "type": "splitcards",
        "heading": "Visit the Lake Oswego showroom",
        "items": [
          {
            "title": "Visit the Lake Oswego showroom",
            "body": "333 S State St, Suite 200. Street parking out front. Every category is filled and running — hot tubs, swim spas, saunas, plunges, and chairs.",
            "image": null,
            "showAddress": true,
            "showHours": true,
            "actions": [
              {
                "label": "Get directions",
                "href": "/visit-us",
                "style": "primary"
              }
            ]
          }
        ]
      },
      {
        "type": "splitcards",
        "eyebrow": "Worth the drive",
        "heading": "Two reasons to come in",
        "items": [
          {
            "title": "See them filled and running",
            "body": "Ten minutes in a seat tells you more than an evening of tabs.",
            "image": null,
            "showAddress": true,
            "showHours": true,
            "actions": [
              {
                "label": "Learn more",
                "href": "/inventory",
                "style": "primary"
              }
            ]
          },
          {
            "title": "Talk to people who install them",
            "body": "Ask about pads, 50-amp circuits, and winter covers — you'll get a plan, not a script.",
            "image": null,
            "showAddress": false,
            "showHours": false,
            "actions": [
              {
                "label": "Learn more",
                "href": "/visit-us",
                "style": "primary"
              }
            ]
          }
        ]
      },
      {
        "type": "steps",
        "eyebrow": "How it works",
        "heading": "From first sit to first soak",
        "items": [
          {
            "title": "Come sit in them",
            "body": "Compare models side by side with a specialist who knows the jet maps."
          },
          {
            "title": "Get the out-the-door number",
            "body": "Spa, delivery, placement, and startup — one page you can take home."
          },
          {
            "title": "We handle the rest",
            "body": "Pad check, delivery window, water chemistry, and a local number after."
          }
        ]
      },
      {
        "type": "faq",
        "eyebrow": "Good questions",
        "heading": "What Portland buyers ask first",
        "items": [
          {
            "q": "How much does a hot tub actually cost?",
            "a": "Most four-to-six person spas landed in a backyard here run from the mid $8,000s to the low $20,000s out the door. We quote one number that includes delivery and setup."
          },
          {
            "q": "What does delivery involve?",
            "a": "We measure gates, grade, and overhead lines, then schedule a crew and crane if the side yard is tight. You are not left with a crate on the driveway."
          },
          {
            "q": "What do I need at home?",
            "a": "A level pad and, for most spas, a dedicated 50-amp circuit. Swim spas and saunas have their own needs — we walk those before you buy."
          },
          {
            "q": "Can I finance it?",
            "a": "Yes, through Wells Fargo Home Projects on qualifying purchases. Checking options in the showroom will not open a hard pull until you apply."
          },
          {
            "q": "Do you deliver outside Lake Oswego?",
            "a": "Yes — Portland, West Linn, Oregon City, Tigard, Tualatin, Sherwood, Lake Grove, Dunthorpe, and Clackamas."
          }
        ]
      },
      {
        "type": "ctaband",
        "eyebrow": "Easy monthly options",
        "heading": "See your financing options",
        "body": "Promotional terms on qualifying spas. Check your options in a couple of minutes — asking will not affect your credit.",
        "actions": [
          {
            "label": "Check my options",
            "href": "/financing",
            "style": "primary"
          },
          {
            "label": "Text (503) 555-0190",
            "href": "sms:+15035550190",
            "style": "secondary"
          }
        ],
        "footnote": "Subject to credit approval. Example payments are estimates, not offers of credit.",
        "tone": "dark"
      },
      {
        "type": "cta",
        "heading": "Text us the seats and the budget",
        "buttonLabel": "Request pricing",
        "subtext": "We reply with in-stock matches and a written total. No mailing list, no second salesperson."
      },
      {
        "type": "trust",
        "items": [
          "Family-run since 2011",
          "Lake Oswego showroom",
          "Licensed delivery crew",
          "4.8★ from 142 Google reviews",
          "Written out-the-door pricing"
        ],
        "logos": []
      },
      {
        "type": "bignumber",
        "value": "15+",
        "label": "years helping Willamette backyards",
        "claim": null
      },
      {
        "type": "countdown",
        "eyebrow": "Harvest soak event",
        "heading": "Complimentary delivery ends November 30",
        "body": "In-stock spas include Metro Portland delivery and a starter chemical kit if you take delivery by the event date.",
        "endsAt": "2026-11-30T17:00:00"
      },
      {
        "type": "ctaband",
        "eyebrow": "Ready when you are",
        "heading": "Come walk the floor this week",
        "body": "Sit in the spas, or start with a text. Either way you get real Lake Oswego pricing without the runaround.",
        "actions": [
          {
            "label": "Request pricing",
            "href": "/find-your-match",
            "style": "primary"
          },
          {
            "label": "Get directions",
            "href": "/visit-us",
            "style": "secondary"
          }
        ],
        "footnote": "Open Monday–Saturday, Sunday 11–4. 333 S State St, Suite 200.",
        "tone": "dark"
      }
    ],
    "disclosures": []
  },
  "integrations": {
    "d1BindingName": "DB",
    "r2BindingName": "PRODUCT_IMAGES",
    "ghl": {
      "enabled": false
    },
    "meta": {
      "enabled": false
    },
    "zaraz": {
      "enabled": false
    },
    "sentry": {
      "enabled": false
    }
  }
};
